### ISSUE TITLE
Failed to download library

### ISSUE THREAD

**Issue by kosme** [KiCad/Connect.pretty#32]
When running cvpcb.

Errors were encountered loading footprints
IO_ERROR: https GET command failed
Cannot get/download Zip archive: 'https://codeload.github.com/KiCad/Housings_TO-92.pretty.git/zip/master'
for library path: 'https://github.com/KiCad/Housings_TO-92.pretty'.
Reason: 'Not found'
from C:/Jenkins/workspace/windows-kicad-msys2-stable/src/kicad-4.0.0-rc1/pcbnew/github/github_plugin.cpp : remote_get_zip() : line 584
![bug-kicad](https://cloud.githubusercontent.com/assets/1418331/11480550/9cd4e32e-975d-11e5-847e-992e1ab7242e.jpg)

**Comment by reportingsjr** [comment]
See my answer in the other PR you commented on. This is from the fp-lib-table getting updated. Updating fp-lib-table will fix this issue.
