### ISSUE TITLE
fail to download the library

### ISSUE THREAD

**Issue by lsaavedr** [KiCad/Connect.pretty#8]
The last version of kicad fail to download the library with this error:
# 

Errors were encountered loading footprints
IO_ERROR: https GET command failed
Cannot get/download Zip archive: 'https://codeload.github.com/KiCad/Connect.pretty.git/zip/master'
for library path: 'https://github.com/KiCad/Connect.pretty.git'.
Reason: 'Not found'
from /build/buildd/kicad-0.201411151246+5284~19~ubuntu14.04.1/kicad/pcbnew/github/github_plugin.cpp : remote_get_zip() : line 548
# 

this seems to be a problem in the repo configuration (and in the kicad default mode of download libraries),

regards,
Luis

**Comment by kosme** [comment]
Same issue on 4.0.0-rc1-stable.

Errors were encountered loading footprints
IO_ERROR: https GET command failed
Cannot get/download Zip archive: 'https://codeload.github.com/KiCad/Housings_TO-92.pretty.git/zip/master'
for library path: 'https://github.com/KiCad/Housings_TO-92.pretty'.
Reason: 'Not found'
from C:/Jenkins/workspace/windows-kicad-msys2-stable/src/kicad-4.0.0-rc1/pcbnew/github/github_plugin.cpp : remote_get_zip() : line 584
![bug-kicad](https://cloud.githubusercontent.com/assets/1418331/11480550/9cd4e32e-975d-11e5-847e-992e1ab7242e.jpg)

**Comment by reportingsjr** [comment]
Those repositories were merged with other ones in preparation for the 4.0.0 release. You need to update you fp-lib-table to remove those and include any new repositories that were created during the merge. (easiest way is to delete all of the github ones, then use the footprint library wizard to add them all at once)

**Comment by jcard0na** [comment]
I wish I knew which fp-lib-table file to remove, and how to launch the footprint library wizard....

**Comment by jcard0na** [comment]
Ah, deleting the file under $HOME/.config/kicad/fp-lib-table and re-launching kicad gives me an informative message with some guidance:

> You have run CvPcb for the first time using the new footprint library table method for finding footprints.  CvPcb has either copied the default table or created an empty table in your home folder.  You must first configure the library table to include all footprint libraries not included with KiCad.  See the "Footprint Library Table" section of the CvPcb documentation for more information.

**Comment by jcard0na** [comment]
...followed by the same error as before.

**Comment by jcard0na** [comment]
Ah turns out you can fix this error from within kicad quite easily:
1. From CVPCB -> Preferences -> Footprint libraries
2. Remove all Global Libraries (Remove Library)
3. 'Append with Wizard'
4. Restart kicad
